import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Amplify } from 'aws-amplify';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

Amplify.configure({
  Auth: {
    Cognito: {
      userPoolId: process.env.
      NEXT_PUBLIC_COGNITO_USER_POOL_ID!,
      userPoolClientId: process.env.
      NEXT_PUBLIC_COGNITO_CLIENT_ID!,
      loginWith: {
        email: true, // email + password
      },
    },
  },
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
